-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 17:31:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GymAppDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GymAppDB` ;

-- -----------------------------------------------------
-- Schema GymAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GymAppDB` DEFAULT CHARACTER SET utf8 ;
USE `GymAppDB` ;

-- -----------------------------------------------------
-- Table `GymAppDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Telefono` VARCHAR(20) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdUsuario`));


-- -----------------------------------------------------
-- Table `GymAppDB`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`Actividad` (
  `IdActividad` INT NOT NULL AUTO_INCREMENT,
  `Denominacion` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdActividad`));


-- -----------------------------------------------------
-- Table `GymAppDB`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`Clase` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`Clase` (
  `IdClase` INT NOT NULL AUTO_INCREMENT,
  `Actividad_IdActividad` INT NOT NULL,
  `Dia` VARCHAR(10) NOT NULL,
  `Horario` TINYINT NOT NULL,
  `Cupo` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdClase`),
  CONSTRAINT `fk_Clase_Actividad1`
    FOREIGN KEY (`Actividad_IdActividad`)
    REFERENCES `GymAppDB`.`Actividad` (`IdActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Clase_Actividad1_idx` ON `GymAppDB`.`Clase` (`Actividad_IdActividad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GymAppDB`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`Reserva` (
  `IdReserva` INT NOT NULL AUTO_INCREMENT,
  `Clase_IdClase` INT NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdReserva`),
  CONSTRAINT `fk_Reserva_Clase1`
    FOREIGN KEY (`Clase_IdClase`)
    REFERENCES `GymAppDB`.`Clase` (`IdClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `GymAppDB`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Reserva_Clase1_idx` ON `GymAppDB`.`Reserva` (`Clase_IdClase` ASC) VISIBLE;

CREATE INDEX `fk_Reserva_Usuario1_idx` ON `GymAppDB`.`Reserva` (`Usuario_IdUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GymAppDB`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`Categoria` (
  `IdCategoria` INT NOT NULL AUTO_INCREMENT,
  `Denominacion` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdCategoria`));


-- -----------------------------------------------------
-- Table `GymAppDB`.`ActividadCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymAppDB`.`ActividadCategoria` ;

CREATE TABLE IF NOT EXISTS `GymAppDB`.`ActividadCategoria` (
  `Categoria_IdCategoria` INT NOT NULL,
  `Actividad_IdActividad` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_ActividadCategoria_Categoria`
    FOREIGN KEY (`Categoria_IdCategoria`)
    REFERENCES `GymAppDB`.`Categoria` (`IdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActividadCategoria_Actividad1`
    FOREIGN KEY (`Actividad_IdActividad`)
    REFERENCES `GymAppDB`.`Actividad` (`IdActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_ActividadCategoria_Categoria_idx` ON `GymAppDB`.`ActividadCategoria` (`Categoria_IdCategoria` ASC) VISIBLE;

CREATE INDEX `fk_ActividadCategoria_Actividad1_idx` ON `GymAppDB`.`ActividadCategoria` (`Actividad_IdActividad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
