# Generated by Django 5.1.2 on 2024-11-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nroDoc',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
